name: 'install-cromwell'
description: 'installs cromwell and womtool locally for jobs that require it'
inputs:
  CROMWELL_VERSION:  # id of input
    description: 'Cromwell Version to download'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set Cromwell env variables
      run: |
        echo "CROMWELL_JAR=${HOME}/cromwell-${{ inputs.CROMWELL_VERSION }}.jar" >> $GITHUB_ENV;
        echo "WOMTOOL_JAR=${HOME}/womtool-${{ inputs.CROMWELL_VERSION }}.jar" >> $GITHUB_ENV;
      shell: bash
    - name: Download Cromwell and Womtools
      run: |
        wget -O $CROMWELL_JAR https://github.com/broadinstitute/cromwell/releases/download/${{ inputs.CROMWELL_VERSION }}/cromwell-${{ inputs.CROMWELL_VERSION }}.jar;
        wget -O $WOMTOOL_JAR https://github.com/broadinstitute/cromwell/releases/download/${{ inputs.CROMWELL_VERSION }}/womtool-${{ inputs.CROMWELL_VERSION }}.jar;
      shell: bash






#
#installCromwell:
#  runs-on: ubuntu-latest
#  name: Cromwell Local Setup
#  steps:
#    - name: Set Cromwell env variables
#      run: |
#        echo "CROMWELL_JAR=${HOME}/cromwell-${{ env.inputs.CROMWELL_VERSION }}.jar" >> $GITHUB_ENV;
#        echo "WOMTOOL_JAR=${HOME}/womtool-${{ env.inputs.CROMWELL_VERSION }}.jar" >> $GITHUB_ENV;
#    - name: Download Cromwell and Womtools
#      run: |
#        wget -O $CROMWELL_JAR https://github.com/broadinstitute/cromwell/releases/download/${{ env.inputs.CROMWELL_VERSION }}/cromwell-${{ env.inputs.CROMWELL_VERSION }}.jar;
#        wget -O $WOMTOOL_JAR https://github.com/broadinstitute/cromwell/releases/download/${{ env.inputs.CROMWELL_VERSION }}/womtool-${{ env.inputs.CROMWELL_VERSION }}.jar;
